name: GitHub 3D Contribution Profile Generator

on:
  schedule:
    - cron: "0 2 * * *" # Runs every day at 2 AM UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate GitHub 3D Contribution Profile
        uses: yoshi389111/github-profile-3d-contrib@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          output_path: profile-3d-contrib

      - name: Commit and Push
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add .
          git commit -m "chore: update 3D contribution graph" || echo "No changes to commit"
          git push
